export const GALLERY = [
  { name: "Sky", year: "2016", img: "/img1.webp" },
  { name: "Sunset", year: "2020", img: "/img2.webp" },
  { name: "Shop", year: "2022", img: "/img3.webp" },
  { name: "Japan", year: "2012", img: "/img4.webp" },
  { name: "Tokyo", year: "2004", img: "/img5.webp" },
  { name: "Fuji", year: "2024", img: "/img6.webp" },
  { name: "Algiers", year: "2016", img: "/img7.webp" },
  { name: "Culture", year: "2012", img: "/img8.webp" },
  { name: "Tlemcen", year: "2014", img: "/img9.webp" },
  { name: "Oran", year: "2015", img: "/img10.webp" },
  { name: "Khemis", year: "2017", img: "/img11.webp" },
  { name: "Clock", year: "2010", img: "/img12.webp" },
  { name: "Coding", year: "2002", img: "/img13.webp" },
  { name: "Cure", year: "2012", img: "/img14.webp" },
  { name: "Cart", year: "2011", img: "/img15.webp" },
  { name: "Grass", year: "2015", img: "/img16.webp" },
];
